### ISSUE TITLE
Does ezc3d can install in Mac?

### ISSUE THREAD

**Issue by curcify** [pyomeca/ezc3d#229] opened 2022-01-10 14:42 UTC
Dear sir
I used CMake to binder in mac.
I made a release folder.
Configure select Unix makefiles-Use default native compilers
And there were wrong message

Found Matlab: /Applications/MATLAB_R2021b.app/extern/include (found version "9.11") found components: MX_LIBRARY 
CMake Error at modules/FindOctave.cmake:143 (message):
  Octave-config could not be found.  Please set the OCTAVE_CONFIG_EXECUTABLE
  variable to the 'octave-config' executable file
Call Stack (most recent call first):
  binding/octave/CMakeLists.txt:4 (find_package)

<img width="939" alt="截圖 2022-01-10 下午10 33 58" src="https://user-images.githubusercontent.com/17661310/148783303-fc5133bf-7d49-4ead-87c7-1984baebdbe5.png">

Why it show ?
Octave-config could not be found.  Please set the OCTAVE_CONFIG_EXECUTABLE
Thanks for your help.

**Comment by pariterre** [comment] 2022-01-10 15:16
Hi there!
Do you actually need Octave? I am not sure why you have both Octave and Matlab... And it seems Octave is not installed on your computer... I suggest to simply uncheck the Octave binder

**Comment by curcify** [comment] 2022-01-10 15:49
Thanks for your suggestion.
But still have problem.
It's show
CMake Deprecation Warning at binding/CMakeLists.txt:9 (cmake_policy):
  The OLD behavior for policy CMP0086 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Looking forward to your response.
Thanks for your help.

**Comment by pariterre** [comment] 2022-01-10 17:09
Hi!
These are warnings, it should work. They are caused by googletest. It is not a problem and that should not prevent from compiling

**Comment by curcify** [comment] 2022-01-10 17:42
Thanks for your response.
But I did not see .mexmaci64 for MacOSX.
The matlab folder is empty.
And run ezc3dRead it show
Unrecognized function or variable 'ezc3dRead'.

**Comment by pariterre** [comment] 2022-01-10 17:44
Hello again :)

Did you actually compiled? CMake is just for preparing the compilation process. Once you `configured`, and `genarated`, you need to navigate (using command lines) to the build folder and type `make` or `make install`

**Comment by curcify** [comment] 2022-01-10 17:57
Hi
you need to navigate (using command lines) to the build folder and type make or make install.
This step was in Cmake or Matlab?
I did not know how to do this step?.
Thanks for yore patience.

**Comment by pariterre** [comment] 2022-01-10 18:32
This is in a terminal (not in CMake nor Matlab). It looks like that
![image](https://user-images.githubusercontent.com/17518525/148819801-c4f17e0f-9e73-48e0-9d5e-f0705949932a.png)

**Comment by curcify** [comment] 2022-01-10 19:16
Dear Pariterre
Could you tell more detail.
I was open the terminal.
<img width="661" alt="截圖 2022-01-11 上午3 11 23" src="https://user-images.githubusercontent.com/17661310/148824899-71bcd6c8-7b96-46c2-90aa-e12924ded99d.png">
I didn't have command lines in CMake.
I also see https://www.youtube.com/watch?v=gWno_NXrITA in windowns.
Would you have mac youtube link?
Or in terminal? Type what's  "make install"? In which folder?
Thank you. Once again.

**Comment by pariterre** [comment] 2022-01-10 19:39
Hi there
You opened the right tool. 

To navigate to your folder you need to use the command `cd PATH`(stands for change directory to PATH). In you case, it looks that the command should read:
`cd /Users/curcifywang/GoogleDrive/Matlab/c3d_read/ezc3d-dev/release`

After that, (assuming you previously hit configure and generate button in CMake), you have to type `make` to build ezc3d or `make install` to build and install. It is possible that `make install` crashes, if it does, we will sort this out when you get there :)

So. in the terminal, it should read more or less like this: 
`cd /Users/curcifywang/GoogleDrive/Matlab/c3d_read/ezc3d-dev/release`
`make`
`make install`

**Comment by pariterre** [comment] 2022-01-10 19:44
Sorry I could not find any tutorial for Mac..

**Comment by curcify** [comment] 2022-01-11 03:32
Hi
(base) curcifywang@CurcifydeMacBook-Pro release % make install
Consolidate compiler generated dependencies of target ezc3d
[ 61%] Built target ezc3d
Consolidate compiler generated dependencies of target ezc3d_matlab_Read
[ 70%] Built target ezc3d_matlab_Read
Consolidate compiler generated dependencies of target ezc3d_matlab_Write
[ 80%] Built target ezc3d_matlab_Write
Consolidate compiler generated dependencies of target create_and_read_example
[ 87%] Built target create_and_read_example
Consolidate compiler generated dependencies of target modify_c3d_example
[ 93%] Built target modify_c3d_example
Consolidate compiler generated dependencies of target force_plate_example
[100%] Built target force_plate_example
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/lib/ezc3d.  Maybe need
  administrative privileges.

It's show CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/lib/ezc3d.  Maybe need
It's can work in matlab ezc3dWrite and ezc3dRead.
Thanks for your strong support.

**Comment by pariterre** [comment] 2022-01-11 03:36
Allright, this is the expected fail.

The reason is that you try to install the binaries in a folder you don't have access to:
`/Applications/Matlab_R2021.bin/toolbox` (The `Matlab_ezc3d_INSTALL_DIR` in cmake). 
You must change this folder to a folder you have the write rights (then you click configure and generate again). After make again, it should work

**Comment by pariterre** [comment] 2022-01-11 03:37
That said, the binary should already exist in the build folder

**Comment by curcify** [comment] 2022-01-11 09:08
Dear Sir
Still have have problem.
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/lib/ezc3d.  Maybe need
  administrative privileges.

Is matlab_ezx3d_INSTALL_DIR question?
All the best

**Comment by pariterre** [comment] 2022-01-11 14:17
That one is the CMAKE_INSTALL_PREFIX, this is basically the same problem, you don't have write access to the folder you used as CMAKE_INSTALL_PREFIX. Change this one, and you should be good to go.

That said, you can also revert back the Matlab folder and use the command: `sudo make install` (notice the sudo) which will require your password (please note that when you type your password, nothing appear on screen). Like that you can install at default CMAKE_INSTALL_PREFIX and default toolbox folder in matlab :)

Enjoy

**Comment by curcify** [comment] 2022-01-11 14:54
Dear Paiterre
All can done will.
Thanks for your patience and strong support.
All the best.

**Comment by pariterre** [comment] 2022-01-11 14:58
Does this mean it works? :)
If so, you can close the issue!

Cheers

**Closed as completed** 2022-01-11 15:00 UTC
